<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["tre_user", "Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Edit note</h1>
</div>

<?php echo $this->getContent(); ?>

<form action="<?php echo "/tre_user/save/" . $tre_note; ?>" class="form-horizontal" method="post">
    <div class="form-group">
        <label for="name">note baru</label>
            <?php echo $this->tag->textField([
                "note_description",
                "class" => "form-control",
                "placeholder"=> "Enter your note here"
            ]); ?>
    </div>

    <?php echo $this->tag->hiddenField("note_id") ?>

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
        </div>
    </div>
</form>
