<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Paginator\Adapter\Model; use trellite2\Models\TreNote;?>
<div class="page-header">

    <p><?php echo $this->flashSession->output(); ?></p>
    <p><?php echo $this->flash->output(); ?></p>

    <h1>Halo <?php echo $this->session->get('AUTH_USERNAME'); ?> !</h1>
    <p><?php echo $this->tag->linkTo(["tre_user/new", "Make new note"]) ?></p>

    <!-- <p><?php echo $this->tag->linkTo(["tre_user/search", "Search tre_user"]) ?></p> -->

</div>

<?php echo $this->getContent() ?>
<?php echo $this->flash->output() ?>

<!-- </form> -->

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>note no.</th>
                <!-- <th>tre_id</th> -->
                
                <th>description</th>
                <!-- <th>note_createdAt</th> -->
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->getItems() as $tre_note): ?>
            <?php if($tre_note['tre_id'] == $this->session->get('AUTH_ID')) : ?>
            <tr>
                <td><?php echo $tre_note['note_id'] ?></td>
                <!-- <td><?php echo $tre_note['tre_id'] ?></td> -->
                <td><?php echo $tre_note['note_description'] ?></td>
                <td><?php echo $tre_note['note_createdAt'] ?></td>

                <td><?php echo $this->tag->linkTo(["tre_user/edit/" . $tre_note['note_id'], "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["tre_user/delete/" . $tre_note['note_id'], "Delete"]); ?></td>
            </tr>
            <?php endif; ?>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->getCurrent(), "/", $page->getTotalItems() ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo(["tre_user/search", "First", 'class' => 'page-link']) ?></li>
                <li><?php echo $this->tag->linkTo(["tre_user/search?page=" . $page->getPrevious(), "Previous", 'class' => 'page-link']) ?></li>
                <li><?php echo $this->tag->linkTo(["tre_user/search?page=" . $page->getNext(), "Next", 'class' => 'page-link']) ?></li>
                <li><?php echo $this->tag->linkTo(["tre_user/search?page=" . $page->getLast(), "Last", 'class' => 'page-link']) ?></li>
            </ul>
        </nav>
    </div>
</div>

