<?php
/**
 * 
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["tre_user", "Go Back"]) ?></li>
        </ul>

        <p><?php echo $this->flashSession->output(); ?></p>
        <p><?php echo $this->flash->output(); ?></p>
    </nav>
</div>

<div class="page-header">
    <h1>Create Note</h1>
</div>

<?php use Phalcon\Tag; echo $this->getContent(); ?>

<form action="create" class="form-horizontal" method="post">
    <div class="form-group">
    <label for="name">new Note</label>
        <?php echo $this->tag->textField([
            "note_description",
            "class" => "form-control",
            "placeholder"=> "Enter your note here"
        ]); ?>
    </div>
</div>

<!-- 
<div class="form-group">
    <label for="fieldTrePassword" class="col-sm-2 control-label">Tre Of Password</label>
    <div class="col-sm-10">
        
    </div>
</div> -->

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
        </div>
    </div>
</form>
