<?php
/**
 * 
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["tre_user/index", "Go Back"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["tre_user/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>
<!-- 
<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Tre</th>
            <th>Tre Of Username</th>
            <th>Tre Of Email</th>
            <th>Tre Of Password</th>
            <th>Tre Of Timestamp</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->getItems() as $tre_user): ?>
            <tr>
                <td><?php echo $tre_user['tre_id'] ?></td>
                <td><?php echo $tre_user['tre_username'] ?></td>
                <td><?php echo $tre_user['tre_email'] ?></td>
                <td><?php echo $tre_user['tre_password'] ?></td>
                <td><?php echo $tre_user['tre_timestamp'] ?></td>

                <td><?php echo $this->tag->linkTo(["tre_user/edit/" . $tre_user['tre_id'], "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["tre_user/delete/" . $tre_user['tre_id'], "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div> -->

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>catatan ke</th>
                <!-- <th>tre_id</th> -->
                
                <th>catatan</th>
                <!-- <th>note_createdAt</th> -->
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->getItems() as $tre_note): ?>
            <?php if($tre_note['tre_id'] == $this->session->get('AUTH_ID')) : ?>
            <tr>
                <td><?php echo $tre_note['note_id'] ?></td>
                <!-- <td><?php echo $tre_note['tre_id'] ?></td> -->
                <td><?php echo $tre_note['note_description'] ?></td>
                <!-- <td><?php echo $tre_note['note_createdAt'] ?></td> -->

                <td><?php echo $this->tag->linkTo(["tre_user/edit/" . $tre_note['note_id'], "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["tre_user/delete/" . $tre_note['note_id'], "Delete"]); ?></td>
            </tr>
            <?php endif; ?>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->getCurrent(), "/", $page->getTotalItems() ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo(["tre_user/search", "First", 'class' => 'page-link']) ?></li>
                <li><?php echo $this->tag->linkTo(["tre_user/search?page=" . $page->getPrevious(), "Previous", 'class' => 'page-link']) ?></li>
                <li><?php echo $this->tag->linkTo(["tre_user/search?page=" . $page->getNext(), "Next", 'class' => 'page-link']) ?></li>
                <li><?php echo $this->tag->linkTo(["tre_user/search?page=" . $page->getLast(), "Last", 'class' => 'page-link']) ?></li>
            </ul>
        </nav>
    </div>
</div>
